mkdocs:
  image: pataquets/mkdocs
  command:
    - "serve"
    - "--dev-addr"
    - "0.0.0.0:8000"
    - "--config-file"
    - "/docs/mkdocs.yml"
  ports:
    - 8000:8000
  volumes:
    - ./:/docs/:ro
